# SPDX-FileCopyrightText: Mark Thurston
#
# SPDX-License-Identifier: Apache-2.0
---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.1.2
    hooks:
      - id: reuse
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: '25.9.0'
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: '7.0.0'
    hooks:
      - id: isort
        name: isort (python)
