# SPDX-FileCopyrightText: Mark Thurston
#
# SPDX-License-Identifier: Apache-2.0
---
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.2
    hooks:
      - id: reuse
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
